// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyzktiekxmhatefihkki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5emt0aWVreG1oYXRlZmloa2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NDEzMjMsImV4cCI6MjA3ODAxNzMyM30.ykQ8uoAsrCUjWi4EMCPMCnjX7iWzQmgWbdaWgo4V1Bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});